### ISSUE TITLE
Improve install instruction

### ISSUE THREAD

**Issue by unreturned** [deckhouse/deckhouse-cli#24]
Maybe will be useful to notice, that we need to run installer by `root`-user to place binary in `/usr/local/bin/`

Also, installer check shasum, but by default this script is not installed

```
bash d8-install.sh
Downloading https://github.com/deckhouse/deckhouse-cli/releases/download/v0.2.1/d8-v0.2.1-linux-amd64.tar.gz
Verifying checksum... d8-install.sh: строка 89: shasum: команда не найдена
```

We need package `libdigest-sha-perl` for Debian-like and something like `perl-Digest-SHA` on CentOS-like

Also, maybe better to switch to `/usr/bin/sha256sum` looks like it exists by default (`coreutils` package)

**Comment by mvasl** [comment]
This has been addressed in https://github.com/deckhouse/deckhouse-cli/pull/41
