### ISSUE TITLE
No support for kubectl plugins

### ISSUE THREAD

**Issue by diafour** [deckhouse/deckhouse-cli#61]
There is a NodeGroupConfiguration example about [Installing the cert-manager plugin for kubectl on master node](https://deckhouse.io/products/kubernetes-platform/documentation/v1/modules/node-manager/examples.html#installing-the-cert-manager-plugin-for-kubectl-on-master-nodes)

After applying this NGC I see the plugin is available:

```
# d8 k plugin list
The following compatible plugins are available:

/usr/local/bin/kubectl-cert_manager
```

Any attempt to use it prints `d8 k` help:

```
# d8 k cert-manager status
...
Usage:
  d8 k [flags] [options]

Use "k <command> --help" for more information about a given command.
Use "d8 k options" for a list of global command-line options (applies to all commands).
```

It seems any non-command argument, i.e.`cert-manager` is considered as wrong. It should treat such arguments as plugin names.

**Comment by mvasl** [comment]
Closing as not planned& Arbitrary plugins are not something we want to support here.
